Add Node.js sample code
Rozetta-RES/signans-client-sample pull request #1
Opened 2021-03-09 07:24 UTC by kei1987

Node.jsのサンプルコードを追加しました。
https://classiii.atlassian.net/browse/CAPI-1787

2021-03-09 08:20 UTC, alxtsg requested changes

2021-03-09 08:20 UTC, alxtsg commented on node-js/src/text-translation.js
> +const tokenPath = '/api/v1/token';
ここも。

2021-03-09 08:20 UTC, alxtsg commented on node-js/src/auth.js
> +const getJwtToken = async (url, accessKey, secretKey) => {
JWT = JSON Web Token
なので、`JwtToken`は`JSON Web Token Token`となります。

`getJWT`（又は`getJwt`）なら良いと思います

2021-03-09 08:20 UTC, alxtsg commented on node-js/src/language-list.js
> +const tokenPath = '/api/v1/token';
JWTを取得するはテキスト翻訳との関係がないので、このパス（URLも）は`node-js/src/auth.js`で指定すれば良いと思います。

2021-03-09 08:20 UTC, alxtsg commented on node-js/src/streaming-stt.js
> +const tokenPath = '/api/v1/token';
ここも。

2021-03-09 08:45 UTC, kei1987 commented on node-js/src/auth.js
> +const getJwtToken = async (url, accessKey, secretKey) => {
修正しました。
https://github.com/Rozetta-RES/signans-client-sample/pull/1/commits/38dd93cb66272bbd4fd574267f80bd306501d079

2021-03-09 08:45 UTC, kei1987 commented on node-js/src/language-list.js
> +const tokenPath = '/api/v1/token';
修正しました。
https://github.com/Rozetta-RES/signans-client-sample/pull/1/commits/38dd93cb66272bbd4fd574267f80bd306501d079

2021-03-09 08:52 UTC, alxtsg requested changes
すみません、JWTを取得できない時表示されるエラーメッセージも変更したいです。

2021-03-09 08:52 UTC, alxtsg commented on node-js/src/language-list.js
> +    console.error('JwtToken error');
`'Unable to get JWT'`に変更したいです。

2021-03-09 08:52 UTC, alxtsg commented on node-js/src/streaming-stt.js
> +    console.error('JwtToken error');
ここも。

2021-03-09 08:52 UTC, alxtsg commented on node-js/src/text-translation.js
> +    console.error('JwtToken error');
ここも。

2021-03-09 08:56 UTC, alxtsg approved these changes

2021-03-09 08:57 UTC, kei1987 commented on node-js/src/language-list.js
> +    console.error('JwtToken error');
すみません、検索が漏れていました。
修正しました。

2021-03-11 06:49 UTC, kei1987 commented
@alxtsg 
ユーザー辞書機能を追加しました。
もし何かあればご指摘ください。

2021-03-11 07:48 UTC, alxtsg requested changes

2021-03-11 07:48 UTC, alxtsg commented on node-js/src/user-dictionary/add-user-dict.js
> +    console.error(`Failed to translate the text: ${message}`);
ここは「辞書項目を追加できなかった」と思います。:thinking:

2021-03-11 07:48 UTC, alxtsg commented on node-js/src/user-dictionary/add-user-dict.js
> +    throw new Error('Failed to translate the text.');
ここも。

2021-03-11 07:48 UTC, alxtsg commented on node-js/src/user-dictionary/delete-user-dict.js
> +    throw new Error('Failed to translate the text.');
第25~26行目、「辞書項目を削除できなかった」。

2021-03-11 07:48 UTC, alxtsg commented on node-js/src/user-dictionary/get-user-dict.js
> +    throw new Error('Failed to translate the text.');
第25~26行目、「辞書項目を取得できなかった」。

2021-03-11 07:48 UTC, alxtsg commented on node-js/src/user-dictionary/update-user-dict.js
> +    throw new Error('Failed to translate the text.');
第34~35行目、「辞書項目を更新できなかった」。

2021-03-11 07:58 UTC, kei1987 commented on node-js/src/user-dictionary/add-user-dict.js
> +    console.error(`Failed to translate the text: ${message}`);
修正しました。
https://github.com/Rozetta-RES/signans-client-sample/pull/1/commits/5f7b7dc9454b3a072b925ce22509b22ba95d5937

2021-03-11 08:35 UTC, alxtsg approved these changes

2021-03-11 09:24 UTC, wuyechang approved these changes

2021-03-12 00:57 UTC, merged